export * from './adr.service';
import { AdrService } from './adr.service';
export * from './appuiConseil.service';
import { AppuiConseilService } from './appuiConseil.service';
export * from './chantier.service';
import { ChantierService } from './chantier.service';
export * from './consigne.service';
import { ConsigneService } from './consigne.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './di82.service';
import { Di82Service } from './di82.service';
export * from './materiel.service';
import { MaterielService } from './materiel.service';
export * from './pdf.service';
import { PdfService } from './pdf.service';
export * from './plancher.service';
import { PlancherService } from './plancher.service';
export * from './poste.service';
import { PosteService } from './poste.service';
export * from './projet.service';
import { ProjetService } from './projet.service';
export * from './risque.service';
import { RisqueService } from './risque.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './zone.service';
import { ZoneService } from './zone.service';
export const APIS = [AdrService, AppuiConseilService, ChantierService, ConsigneService, DefaultService, Di82Service, MaterielService, PdfService, PlancherService, PosteService, ProjetService, RisqueService, UserService, ZoneService];
